# JSP Configuration
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# Disable Database (IMPORTANT for deployment)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Server Port (Render uses dynamic port)
server.port=${PORT:8080}

# File Upload Settings
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

# Upload directory
student.photos.upload.dir=uploads/